### ISSUE TITLE
How to use WaveIO

### ISSUE THREAD

**Issue by dustinlacewell** [robdunn4/QSpice#3]
I'm a new hobby EE looking to learn about DIY modular synthesis. Can you share some information about how to get your Wave IO stuff working with QSpice? Thanks a ton.

**Comment by robdunn4** [comment]
Copy the contents of the WavIO folder (and samples subfolder) to your PC.  Open the demo files with QSpice for examples of using the components.  Let me know if you have questions.

**Comment by dustinlacewell** [comment]
@robdunn4 Where on my PC? Somewhere in the QSpice install? 🙏

**Comment by robdunn4** [comment]
There's nothing special about the code; it's simply a QSpice project so put it in a new empty folder wherever you want to keep projects.  But don't use the QSpice installation folder -- it's deleted/cleared when you install new QSpice releases.
